# Generated by Django 5.1.7 on 2025-03-24 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("lexema_post", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="post",
            old_name="comments",
            new_name="comments_count",
        ),
    ]
