# Generated by Django 5.1.7 on 2025-03-26 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lexema_post", "0002_rename_comments_post_comments_count"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="content",
            field=models.TextField(blank=True, null=True),
        ),
    ]
