# Generated by Django 5.1.7 on 2025-03-12 16:41

import lexema_post.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lexema_post', '0002_postimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postimage',
            name='image',
            field=models.ImageField(upload_to=lexema_post.models.post_image_upload_to),
        ),
    ]
