# Generated by Django 5.1.7 on 2025-03-21 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("lexema_user", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="user",
            table="lexema_app_users",
        ),
    ]
