# Generated by Django 5.1.7 on 2025-03-15 18:10

import django.core.validators
import django.db.models.deletion
import lexema_profile.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(150)])),
                ('gender', models.CharField(blank=True, max_length=50, null=True)),
                ('phone', models.CharField(blank=True, max_length=50, null=True)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('address', models.JSONField(blank=True, null=True)),
                ('education', models.CharField(blank=True, max_length=255, null=True)),
                ('company', models.JSONField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Профиль',
                'verbose_name_plural': 'Профили',
                'db_table': 'lexema_app_profile',
            },
        ),
        migrations.CreateModel(
            name='ProfileImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar_image', models.ImageField(blank=True, null=True, upload_to='', verbose_name=lexema_profile.models.profile_image_upload_to)),
                ('main_page_image', models.ImageField(blank=True, null=True, upload_to='', verbose_name=lexema_profile.models.profile_image_upload_to)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lexema_profile.profile')),
            ],
            options={
                'verbose_name': 'Изображение профиля',
                'verbose_name_plural': 'Изображения профилей',
                'db_table': 'lexema_app_profile_images',
            },
        ),
    ]
