# Generated by Django 5.1.7 on 2025-03-26 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lexema_profile", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="signature",
            field=models.TextField(blank=True, null=True),
        ),
    ]
