# Generated by Django 5.1.7 on 2025-03-31 07:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lexema_profile", "0002_profile_signature"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profileimages",
            name="profile",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="images",
                to="lexema_profile.profile",
            ),
        ),
    ]
