# Generated by Django 5.1.7 on 2025-03-15 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lexema_friends', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friends',
            name='status',
            field=models.CharField(choices=[('pending', 'Отправлено'), ('accepted', 'Подтверждено'), ('rejected', 'Отклонено')], default='pending', max_length=50),
        ),
    ]
