# Generated by Django 5.1.7 on 2025-04-03 17:15

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "lexema_friends",
            "0002_alter_friends_created_at_alter_friends_friend_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Friends",
            new_name="Friend",
        ),
    ]
